vermin: DiningRoom.cpp Downstairs.cpp DownstairsBathroom.cpp DownstairsHallway.cpp Enums.cpp FamilyRoom.cpp InputValidator.cpp Kitchen.cpp Ledge.cpp MasterBathroom.cpp MasterBedroom.cpp Menu.cpp NorthBedroom.cpp Room.cpp SouthBedroom.cpp Study.cpp Upstairs.cpp UpstairsBathroom.cpp UpstairsHallway.cpp Vermin.cpp Vestibule.cpp
	g++ -std=c++11 DiningRoom.cpp Downstairs.cpp DownstairsBathroom.cpp DownstairsHallway.cpp Enums.cpp FamilyRoom.cpp InputValidator.cpp Kitchen.cpp Ledge.cpp MasterBathroom.cpp MasterBedroom.cpp Menu.cpp NorthBedroom.cpp Room.cpp SouthBedroom.cpp Study.cpp Upstairs.cpp UpstairsBathroom.cpp UpstairsHallway.cpp Vermin.cpp Vestibule.cpp -o vermin

clean: 
	rm *.o *.out output


	
