battle: Barbarian.hpp Barbarian.cpp BlueMen.cpp BlueMen.hpp Creature.cpp Creature.hpp Dice.cpp Dice.hpp HarryPotter.hpp HarryPotter.cpp InputValidator.hpp InputValidator.cpp Main.cpp Main.hpp Medusa.cpp Medusa.hpp Menu.cpp Menu.hpp Queue.hpp Queue.cpp Vampire.cpp Vampire.hpp
	g++ -std=c++11 Barbarian.cpp BlueMen.cpp Creature.cpp Dice.cpp HarryPotter.cpp InputValidator.cpp Main.cpp Medusa.cpp Menu.cpp Queue.cpp Vampire.cpp -o Battle

clean: 
	rm *.o *.out output
