#Program Name: makefile
#Author: Jon Raleigh
#Date: 5/14/17
#Description: makefile

LinkedList: main.hpp menu.cpp NumberList.cpp inputValidator.cpp
	g++ -std=c++11 main.cpp menu.cpp NumberList.cpp inputValidator.cpp -o LinkedList

clean:
	rm *.o, *.out ouput 
