# Program Name : makefile
# Author : Jon Raleigh
# Date : 4/16/17
# Description : makefile

langton: langton.cpp board.cpp ant.cpp menu.cpp inputValidator.cpp
	g++ -std=c++11 langton.cpp board.cpp ant.cpp menu.cpp inputValidator.cpp -o langton

clean:
	rm *.o *.out output

