#Program Name : makefile
#Author: Jon Raleigh
#Date : 4/30/17
#Description : makefile

osuinfosystem : Main.cpp People.cpp Instructor.cpp Student.cpp Buildings.cpp menu.cpp inputValidator.cpp University.cpp
	g++ -std=c++11 Main.cpp People.cpp Instructor.cpp Student.cpp Buildings.cpp  menu.cpp inputValidator.cpp University.cpp -o osuinfosystem

clean:
	rm *.o *.out output

