#Program Name : makefile
#Author: Jon Raleigh
#Date: 5/7/17
#Description : makefile

recursive: recursive.cpp menu.cpp inputValidator.cpp
	g++ -std=c++11 recursive.cpp menu.cpp inputValidator.cpp -o recursive

clean: 
	rm *.o *.out  output
