SearchAndSort: InputValidator.cpp InputValidator.hpp Menu.cpp Menu.hpp SearchAndSort.cpp SearchAndSort.hpp 
	g++ -std=c++11 InputValidator.cpp Menu.cpp SearchAndSort.cpp -o SearchAndSort

clean:
	rm *.o *.out output

