# Program Name : makefile
# Author : Jon Raleigh
# Date : 4/9/17
# Description : makefile.

matrix: main.cpp determinant.cpp readMatrix.cpp
	g++ main.cpp determinant.cpp readMatrix.cpp -o matrix 	

clean:
	rm *.o *.out output
