#Program Name : makefile
#Author: Jon Raleigh
#Date 5/14/17
#Description: makefile

Universe: Universe.cpp menu.cpp inputValidator.cpp Barbarian.cpp BlueMen.cpp Creature.cpp Dice.cpp HarryPotter.cpp Medusa.cpp Vampire.cpp Creature.hpp
	g++ -std=c++11 Universe.cpp menu.cpp inputValidator.cpp Barbarian.cpp BlueMen.cpp Creature.cpp Dice.cpp HarryPotter.cpp Medusa.cpp Vampire.cpp -o Universe

clean: 
	rm *.o *.out output
