#Program Name: makefile
#Author: Jon Raleigh
#Date : 4/30/17
#Description: makefile

grocerylist: Main.cpp List.cpp Item.cpp menu.cpp inputValidator.cpp
	g++ -std=c++11 Main.cpp List.cpp Item.cpp menu.cpp inputValidator.cpp -o grocerylist

clean:
	rm *.o *.out output

