# Program Name : makefile
# Author : Jon Raleigh
# Date : 4/23/17
# Description : makefile

dicegame : main.cpp game.cpp die.cpp loadedDie.cpp inputValidator.cpp menu.cpp
	g++ -std=c++11 main.cpp game.cpp die.cpp loadedDie.cpp inputValidator.cpp menu.cpp -o dicegame

clean:
	rm *.o *.out output


